version: '3.6'

services:
  busboardil:
    build:
      context: .
    container_name: busboardil
    restart: always
    tty: true
    ports:
      - "80"
  db:
    image: mariadb:10.1
    container_name: busboardil-db
    environment:
      - MYSQL_DATABASE=busboardil
      - MYSQL_USER=busboardil
      - MYSQL_PASSWORD=busboardil
      - MYSQL_ROOT_PASSWORD=fKc8dlZqhNOucISGiZA6
    volumes:
      - ${DB_VOLUME:-./busboardil-database}:/var/lib/mysql
    restart: always

